Fix Document URL Link not exists
kudobuilder/kudo.dev pull request #102
Opened 2019-11-26 13:05 UTC by sharego

Kudo repository master branch (since release 0.8) changed kudo example config, this document links all not exists now. I checked the config examples it work on release/0.7, this commit fixed the url link

2019-11-26 18:37 UTC, alenkacz requested changes
Thanks for the PR! I think the right solution here is to remove the links altogether. Could you please make that change? Those examples are obsolete and we're not keeping them up to date anymore. I am not sure linking here actually adds that much value

2019-11-27 01:07 UTC, sharego commented
Thank you review very much. I also think about that, this document shows some concepts in kudo, just for that sounds the link is not out of date.

If it is sure, need to deprecate this example,  can we use the [`first-operator`](https://github.com/kudobuilder/operators/blob/master/repository/first-operator/operator) as a example?

2019-11-28 17:22 UTC, alenkacz commented
@sharego yes, but that's a bit different format than the CRDs so we cannot link it from here. Just remove the three links from this page you edited and this PR is good to merge. We can then think about how to improve the docs overall. Thank you!

2019-12-02 14:28 UTC, meichstedt approved these changes
lgtm. @alenkacz can you re-review please?

2019-12-03 08:24 UTC, alenkacz approved these changes
LGTM

2019-12-03 08:25 UTC, merged