Blogs do NOT need entry into vuepress config
kudobuilder/kudo.dev pull request #271
Opened 2020-07-13 19:41 UTC by kensipe

Entries into vuepress config.js isn't necessary

Signed-off-by: Ken Sipe <kensipe@gmail.com>

2020-07-13 20:28 UTC, mattj-io commented
I'm assuming the second part of my blog will automagically appear in the sidebar after this is merged ?

2020-07-13 21:47 UTC, kensipe commented
@mattj-io it already has :)

2020-07-13 22:49 UTC, mattj-io commented
Hmm, I'm not seeing it in the sidebar ...

2020-07-14 07:56 UTC, ANeumann82 approved these changes
The entries are sorted by the date inside the file then, I assume?

2020-07-14 07:57 UTC, ANeumann82 requested changes
Well - I had a look at the preview: https://deploy-preview-271--kudo-www.netlify.app/blog/

The blog entries show up, but the sidebar is empty, so it seems we still have to have the config.js entries?

2020-07-14 12:18 UTC, mattj-io commented
I just opened #272 which works for me to create sidebars dynamically from a folder structure. I couldn't find any reference to Vuepress doing this natively @kensipe - have I missed something ?

2020-07-14 17:19 UTC, meichstedt requested changes
I don't see how this will create dynamic sidebar entries. Is this missing a commit maybe?

2020-07-17 14:54 UTC, kensipe commented
I see that I missed the sidebar... but like the core of @mattj-io solution and will transition to completing that.
There seem to be 2 approaches to resolve dynamic content (lose use of that phrase).   For the 2 examples I'm aware of I see them as very different.  1 needs to clone git repos and pull content... the other has a growing list of content in a folder that is local to the repo...  IMO it would be great to keep things as simple as possible and the solution provided by Matt does that.  And the solution Marcin put together is necessary for the problem he was solving.  Hopefully we can agree that Matt's approach is what we will use for local content and Marcin's solution is for anything we pull from external repos.

2020-07-17 14:54 UTC, closed without merging