Add dynamic sidebar functionality
kudobuilder/kudo.dev pull request #272
Opened 2020-07-14 12:17 UTC by mattj-io

Signed-off-by: Matt Jarvis <matt@mattjarvis.org.uk>

**What this PR does / why we need it**:

With reference to #271, which doesn't work for me or @ANeumann82, I did some digging on dynamic sidebar creation from a folder. Happy to be proved wrong, but there doesn't seem to be a way of doing this natively in Vuepress. This PR adds dynamic sidebar generation via a function in config.js, currently only for the blog

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

2020-07-14 12:50 UTC, ANeumann82 approved these changes
Nice! lgtm

2020-07-14 17:20 UTC, meichstedt submitted a review, later dismissed
Thanks @mattj-io!

Any chance we could align this solution with the one for [operator docs](https://github.com/kudobuilder/kudo.dev/blob/master/scripts/embed-operator-docs.sh) in the scripts folder?

That existing solution generates a js file as a build step and the results are referenced in the config.js like this:
```
{
  title: 'Cassandra',
  children: require('./cassandra').children
},
```

2020-07-14 17:52 UTC, mattj-io commented
Whilst I could re-write this in bash, auto-generating js by calling external bash scripts is pretty horrific IMO. I can understand why we might want to do that when we want to pull in files from other repositories  ( although git submodules ... ). The two use cases are different, but open to argument !

2020-07-17 14:59 UTC, kensipe commented
There seem to be 2 approaches to resolve dynamic content (lose use of that phrase).   For the 2 examples I'm aware of I see them as very different.  1 needs to clone git repos and pull content... the other has a growing list of content in a folder that is local to the repo...  IMO it would be great to keep things as simple as possible and the solution provided by Matt does that.  And the solution Marcin put together is necessary for the problem he was solving.  Hopefully we can agree that Matt's approach is what we will use for local content and Marcin's solution is for anything we pull from external repos.

2020-07-17 15:11 UTC, kensipe requested changes
Issues with current solution here:
1. defined `const extension` is not used
2. path assumptions for `getSideBar` are too constraining and requires user to have implementation knowledge.   
otherwise lgtm

I'll push an update

2020-07-17 15:25 UTC, mattj-io commented
Good point on the unused constant. I started doing it one way and then realised I could just do that in the filter.

2020-07-17 15:46 UTC, kensipe commented
@mattj-io didn't mean to hijack it from you.  I anticipated that it was end of day friday for you and wanted to move the ball forward.  nice work!

2020-07-17 15:47 UTC, kensipe approved these changes

2020-07-17 15:48 UTC, kensipe commented
while we potentially could debate consistency etc.. this change makes life better for blog contributors!  thank you!

2020-07-17 16:06 UTC, meichstedt approved these changes
Thanks Matt & Ken!

Added a comment for a follow-up but let's discuss that later.

2020-07-17 16:06 UTC, meichstedt commented on content/.vuepress/config.js
> +        item.toLowerCase() != "readme.md" &&
I guess this is fine for now wrt how we are using the readme's.

Just wondering though – do we actually want to exclude the readme? We could also use them as intended: For vuepress, the README is basically the index.html.

What vuepress will do for a folder like this:
```
/developing-operators/
  README.md
  something-extra.md
```

is to generate this:
```
/developing-operators/index.html <-- that's the readme
/developing-operators/something-extra.html
```

so the README.md naturally will be accessible via `https://kudo.dev/docs/developing-operators/`. This is what we would ideally do; it's the starting page for that section. However, we ended up creating a `getting-started` instead of a README, and therefore `/developing-operators/` is a 404.

We should probably merge this as is and fix the rest in a follow-up, since we would need to add redirects if we renamed the getting-started to README, and would need to include the README as the first child in the sidebar … this warrants an extra discussion.

2020-07-17 16:27 UTC, kensipe commented on content/.vuepress/config.js
> +        item.toLowerCase() != "readme.md" &&
always learning... that makes sense!

2020-07-17 16:28 UTC, merged